<Project Sdk="Aspire.AppHost.Sdk/13.6.1">

  <ItemGroup>
    <ProjectReference Include="..\CleanArchitectureSkeleton.Api\CleanArchitectureSkeleton.Api.csproj" />
    <ProjectReference Include="..\CleanArchitectureSkeleton.Web\CleanArchitectureSkeleton.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="Aspire.Hosting.Kafka" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>2c9069d6-d005-4134-b401-b3c8d76f1ff6</UserSecretsId>
  </PropertyGroup>

</Project>
